version: '1.0'

services:
  enformion-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: enformion-mcp:latest
    ports:
      - "8000:8000"
    environment:
      GALAXY_AP_NAME: your_profile_name
      GALAXY_AP_PASSWORD: your_profile_password
    runtime: python
    startCommand:
      command: ["python", "main.py"]
